services:
  plugin-license-finder:
    build:
      context: ../../backend
      dockerfile: plugins/license-finder/.cloud/docker/Dockerfile
      target: plugin-dev
      args:
        - PLUGINNAME=license-finder
    image: codeclarityce/license-finder-dev:latest
    restart: always
    volumes:
      - ../../backend:/codeclarity
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      adminer:
        condition: service_started
    env_file:
      - ../../.cloud/env/.env.dev

volumes:
  projects:
