services:
  plugin-js-license:
    build:
      context: ../../backend
      dockerfile: plugins/js-license/.cloud/docker/Dockerfile
      target: plugin-dev
      args:
        - PLUGINNAME=js-license
    image: ceherzog/js-license-dev:latest
    restart: always
    volumes:
      - ../../backend:/codeclarity
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      pg_bouncer:
        condition: service_started
      adminer:
        condition: service_started
    env_file:
      - ../../.cloud/env/.env.dev

volumes:
  projects:
